apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ev-client
  template:
    metadata:
      labels:
        app: ev-client
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ev-client
        image: amoghk04/ev-client:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://escapeverse-server:3001"
        - name: VITE_WS_URL
          value: "ws://escapeverse-server:3002"
        - name: VITE_HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
            ephemeral-storage: "1024Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ev-client
spec:
  type: NodePort
  selector:
    app: ev-client
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30080