apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ev-server
  template:
    metadata:
      labels:
        app: ev-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: server
        image: amoghk04/ev-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 3002
          name: websocket
        env:
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "512Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ev-server
spec:
  type: NodePort
  selector:
    app: ev-server
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30001
    - name: websocket
      port: 3002
      targetPort: 3002
      nodePort: 30002