name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key
          echo -e "Host gcp-vm\n  HostName ${{ secrets.GCP_VM_IP }}\n  User ${{ secrets.GCP_VM_USER }}\n  IdentityFile ~/.ssh/gcp_key\n  StrictHostKeyChecking=no" > ~/.ssh/config

      - name: Pull latest code on GCP VM
        run: |
          ssh gcp-vm << 'EOF'
            cd /home/amogh/DevOps
            git pull origin main
          EOF
