on:
  push:
    "main"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
      - name: start
        run: npm run start
      - name: build
        run: npm run build