name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./escapeverse
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./escapeverse/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint || npm run lint:fix

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./escapeverse
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./escapeverse/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests with coverage
        run: npm test -- --coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./escapeverse/coverage/
          compression-level: 6

  accessibility-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./escapeverse
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./escapeverse/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install axe-core
        run: npm install --save-dev axe-core @axe-core/react jest-axe
      - name: Run accessibility tests
        run: npm test -- --testPathPattern="accessibility"

  visual-regression-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./escapeverse
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./escapeverse/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build app
        run: npm run build
      - name: Serve app
        run: npx serve -s build &
      - name: Run visual tests
        run: npx playwright test
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-test-screenshots
          path: ./escapeverse/test-results/
          compression-level: 6

  responsive-design-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./escapeverse
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./escapeverse/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run responsive tests
        run: |
          npx playwright test --project=Desktop Chrome
          npx playwright test --project=Desktop Firefox
          npx playwright test --project=Tablet
          npx playwright test --project=Mobile
